In [4]:
import pandas as pd
import numpy as np
import xarray as xr
from loess import loess_1d
from scipy import interp

In [3]:
nc2020loc = r"C:\Users\ellye\OneDrive - Imperial College London\Energy System Comparison\Renewables.ninja\VWF-PYTHON ELLYESS\data\2020.nc"

data = xr.open_dataset(nc2020loc)

powerCurveFileLoc = r'C:\Users\ellye\OneDrive - Imperial College London\Energy System Comparison\Renewables.ninja\data\Wind Turbine Power Curves ~ 8 (0.2ms with 0.20 w smoother).csv'
powerCurveFile = pd.read_csv(powerCurveFileLoc)

windFarmFileLoc = r'C:\Users\ellye\OneDrive - Imperial College London\Energy System Comparison\Renewables.ninja\VWF CODE 2020-02-11\RUN\Malte_Offshore_Farms_Gamesa14.csv'
windFarmCols = ['id', 'country', 'name', 'name2', 'lat', 'lon', 'altitude', 'offshore', 'height', 'turbine', 'count', 'kw', 'capacity', 'date', 'status', 'developer', 'operator', 'owner', 'year', 'PR']
wf = pd.read_csv(windFarmFileLoc)
new_names_map = {wf.columns[i]:windFarmCols[i] for i in range(len(windFarmCols))}
wf.rename(new_names_map, axis=1, inplace=True)

wf

id   country                                               name  \
0    1503   England                                             Barrow   
1   12051  Scotland                                           Beatrice   
2   16663   England                                     Blyth Offshore   
3    1507     Wales                                         Burbo Bank   
4   10684     Wales                                         Burbo Bank   
5   10776   England                          Dogger Bank Creyke Beck A   
6   16773   England                          Dogger Bank Creyke Beck B   
7   16689   England                             Dogger Bank Teesside A   
8   12072   England                                            Dudgeon   
9   16790   England                                    East Anglia One   
10  16700   England                                  East Anglia Three   
11  16693   England                                    East Anglia Two   
12  16769  Scotland                                              EOWDC   
13  16521  Scotland  Forthwind Offshore Wind Demonstration Project - 2   
14  16770   England                                           Galloper   
15  30019   England                                 Galloper Extension   
16   1615   England                                  Greater Gabbard 1   
17   1601   England                                   Gunfleet Sands 1   
18  16762   England                     Gunfleet Sands 3 Demonstration   
19   7389     Wales                                        Gwynt y Môr   
20  16677   England                   Hornsea Project One - Heron Wind   
21  16530   England     Hornsea Project Two - Breesea and Optimus Wind   
22  16685   England                              Hornsea Project Three   
23  16672   England                               Hornsea Project Four   
24  12070   England                                     Humber Gateway   
25  16758  Scotland                         Hywind Scotland Pilot Park   
26  12052  Scotland                                          Inch Cape   
27   1504   England                                      Kentish Flats   
28  17376  Scotland    Kincardine Offshore Windfarm Offshore Wind Farm   
29  10526   England                                              Lincs   
30   1574   England                                       London Array   
31   7390   England                             Lynn and Inner Dowsing   
32  16664  Scotland                                   Fife Energy Park   
33  16772  Scotland                                         Moray East   
34  19950  Scotland                                         Moray West   
35  12054  Scotland                                   Neart na Gaoithe   
36  16687   England                                     Norfolk Boreas   
37  16698   England                                   Norfolk Vanguard   
38   7391     Wales                                        North Hoyle   
39   1629   England                                            Ormonde   
40  12071   England                                          Race Bank   
41  16761   England                                            Rampion   
42  10665     Wales                                         Rhyl Flats   
43   7392   England                                         Robin Rigg   
44   1506   England                                       Scroby Sands   
45   7394   England                                   Sheringham Shoal   
46  16690   England                             Dogger Bank Teesside B   
47   6353   England                                           Teesside   
48   1623   England                                             Thanet   
49  16670   England                                           Thanet 2   
50  10786   England                             Triton Knoll Wind Farm   
51   7395   England                                             Walney   
52  16598   England                                   Walney Extension   
53   7396  

In [3]:
A = data.A
z = data.z
dt = data.time.dt.hour
speed = np.zeros((len(dt), len(wf.name)))


In [53]:
# for h in range(len(dt)):
for h in range(2):
    s = speed[h,]
    
    all_heights = wf.height.unique()
    for height in all_heights:
        print(height)
        w = A[h,:,:] * np.log(height / z[h,:,:])
        print(w)
        
        my_farms = wf.height == 144
        
#         zout, wout = loess_1d.loess_1d(w.values, w.lat*w.lon, xnew=None, degree=2, frac=0.5,
#                       npoints=None)
        
        
    wnd_spd = ds[from_name] * (
        np.log(to_height / ds["roughness"]) / np.log(from_height / ds["roughness"])
    )

144
<xarray.DataArray (lat: 361, lon: 576)>
array([[5.1199   , 5.1331267, 5.1484065, ..., 5.0809817, 5.092751 ,
        5.1064153],
       [5.1901336, 5.197009 , 5.2049913, ..., 5.1714945, 5.1774073,
        5.1832776],
       [6.8393326, 6.865141 , 6.892149 , ..., 6.7700496, 6.792873 ,
        6.8142247],
       ...,
       [6.1504946, 6.2124987, 6.276677 , ..., 5.973452 , 6.0304885,
        6.0900483],
       [4.640082 , 4.6788464, 4.717778 , ..., 4.5324655, 4.5676165,
        4.603455 ],
       [4.5974336, 4.614113 , 4.630634 , ..., 4.553614 , 4.567463 ,
        4.582226 ]], dtype=float32)
Coordinates:
  * lat      (lat) float64 -90.0 -89.5 -89.0 -88.5 -88.0 ... 88.5 89.0 89.5 90.0
  * lon      (lon) float64 -180.0 -179.4 -178.8 -178.1 ... 178.1 178.8 179.4
    time     datetime64[ns] 2020-01-01T00:30:00


IndexError: index 380 is out of bounds for axis 0 with size 361

In [42]:
w = A[1,:,:] * np.log(height / z[1,:,:])
w

<xarray.DataArray (lat: 361, lon: 576)>
array([[5.3403764, 5.357235 , 5.373837 , ..., 5.2957687, 5.3097377,
        5.3245897],
       [5.358769 , 5.365473 , 5.3744855, ..., 5.340322 , 5.346176 ,
        5.351902 ],
       [6.878689 , 6.902794 , 6.9277883, ..., 6.8123293, 6.8335724,
        6.8555326],
       ...,
       [5.443143 , 5.500542 , 5.5587277, ..., 5.2837543, 5.3350587,
        5.38725  ],
       [3.9604802, 3.9985042, 4.037807 , ..., 3.8512034, 3.8867004,
        3.9223478],
       [3.982477 , 3.9969964, 4.011509 , ..., 3.943289 , 3.955516 ,
        3.968428 ]], dtype=float32)
Coordinates:
  * lat      (lat) float64 -90.0 -89.5 -89.0 -88.5 -88.0 ... 88.5 89.0 89.5 90.0
  * lon      (lon) float64 -180.0 -179.4 -178.8 -178.1 ... 178.1 178.8 179.4
    time     datetime64[ns] 2020-01-01T01:30:00

In [52]:
np.shape(w)

(361, 576)

In [51]:
np.shape(w.lat * w.lon)

(361, 576)

In [9]:
data.lat

<xarray.DataArray 'lat' (lat: 361)>
array([-90. , -89.5, -89. , ...,  89. ,  89.5,  90. ])
Coordinates:
  * lat      (lat) float64 -90.0 -89.5 -89.0 -88.5 -88.0 ... 88.5 89.0 89.5 90.0
Attributes:
    long_name:    latitude
    units:        degrees_north
    vmax:         1000000000000000.0
    vmin:         -1000000000000000.0
    valid_range:  [-1.e+15  1.e+15]

In [47]:
A[1,:,:]

<xarray.DataArray 'A' (lat: 361, lon: 576)>
[207936 values with dtype=float32]
Coordinates:
  * lat      (lat) float64 -90.0 -89.5 -89.0 -88.5 -88.0 ... 88.5 89.0 89.5 90.0
  * lon      (lon) float64 -180.0 -179.4 -178.8 -178.1 ... 178.1 178.8 179.4
    time     datetime64[ns] 2020-01-01T01:30:00
Attributes:
    units:           m s-1
    fmissing_value:  1000000000000000.0
    standard_name:   2-meter_eastward_wind
    vmax:            1000000000000000.0
    vmin:            -1000000000000000.0
    valid_range:     [-1.e+15  1.e+15]
    long_name:       Scale factor for log-law extrapolation: W = A log(h / z)

In [ ]:
len(np.asarray(data.lon))

In [ ]:
len(np.asarray(data.lat))

In [ ]:
data